export const plansData = [
  {
    id: 'trans-star',
    name: 'Trans Star',
    duration: '30 Days',
    price: 259,
    usersType: 'single',
    tagline: 'Perfect starter plan for individual transporters managing basic operations.',
    limits: {
      users: 'Up to 1',
      companies: 'Up to 1',
      branches: 'Up to 1',
      bilties: 60,
      invoices: 30,
      loadingSlips: 60,
    },
  },
  {
    id: 'trans-ride',
    name: 'Trans Ride',
    duration: '90 Days',
    price: 659,
    usersType: 'single',
    tagline: 'Ideal quarterly plan for solo operators with growing documentation needs.',
    limits: {
      users: 'Up to 1',
      companies: 'Up to 1',
      branches: 'Up to 1',
      bilties: 180,
      invoices: 90,
      loadingSlips: 180,
    },
  },
  {
    id: 'trans-drive',
    name: 'Trans Drive',
    duration: '180 Days',
    price: 1189,
    usersType: 'single',
    tagline: 'Half-yearly value plan for consistent individual transport businesses.',
    limits: {
      users: 'Up to 1',
      companies: 'Up to 1',
      branches: 'Up to 1',
      bilties: 360,
      invoices: 180,
      loadingSlips: 360,
    },
  },
  {
    id: 'trans-fly',
    name: 'Trans Fly',
    duration: '365 Days',
    price: 1979,
    usersType: 'single',
    tagline: 'Best annual plan for solo owners seeking long-term savings and stability.',
    limits: {
      users: 'Up to 1',
      companies: 'Up to 1',
      branches: 'Up to 1',
      bilties: 720,
      invoices: 360,
      loadingSlips: 720,
    },
  },

  // 🚚 Business Plans
  {
    id: 'trans-mileage',
    name: 'Trans Mileage',
    duration: '30 Days',
    price: 659,
    usersType: 'business',
    tagline: 'Entry-level business plan for small teams with multiple branches.',
    limits: {
      users: 'Up to 6',
      companies: 'Up to 2',
      branches: 'Up to 4',
      bilties: 200,
      invoices: 100,
      loadingSlips: 200,
    },
  },
  {
    id: 'trans-highway',
    name: 'Trans Highway',
    duration: '90 Days',
    price: 1719,
    usersType: 'business',
    tagline: 'Quarterly business plan built for smooth, high-volume operations.',
    limits: {
      users: 'Up to 6',
      companies: 'Up to 2',
      branches: 'Up to 4',
      bilties: 600,
      invoices: 300,
      loadingSlips: 600,
    },
  },
  {
    id: 'trans-express',
    name: 'Trans Express',
    duration: '180 Days',
    price: 3299,
    usersType: 'business',
    tagline: 'Powerful half-yearly plan for fast-growing transport businesses.',
    limits: {
      users: 'Up to 6',
      companies: 'Up to 2',
      branches: 'Up to 4',
      bilties: 1200,
      invoices: 600,
      loadingSlips: 1200,
    },
  },
  {
    id: 'trans-turbo',
    name: 'Trans Turbo',
    duration: '365 Days',
    price: 5939,
    usersType: 'business',
    current: true,
    tagline: 'Ultimate annual plan for high-scale transport businesses and teams.',
    limits: {
      users: 'Up to 6',
      companies: 'Up to 2',
      branches: 'Up to 4',
      bilties: 2400,
      invoices: 1200,
      loadingSlips: 2400,
    },
  },
];
